### ISSUE TITLE
setting mesh color broken

### ISSUE THREAD

**Issue by haehn** [niivue/niivue#1256]
It seems that the latest commit

https://github.com/niivue/niivue/commit/0b82dab2884a0472fa1a682c4d0638ad59a90e7d

broke the following

![Image](https://github.com/user-attachments/assets/4168892d-2345-4b3f-ad53-376a33e324b0)

with this addition:

![Image](https://github.com/user-attachments/assets/ef55c8a7-c2ef-4d86-bd01-c0586db65cf9)

**Comment by hanayik** [comment]
@haehn , niivue 0.53.1 should solve this. It is available on NPM now.

**Comment by neurolabusc** [comment]
@hanayik the bug introduced by [0b82dab](https://github.com/niivue/niivue/commit/0b82dab2884a0472fa1a682c4d0638ad59a90e7d) is still not resolved, as seen by adjusting the color slider in the mesh [live demo](https://niivue.github.io/niivue/features/meshes.html). The upcoming commit (add to an open PR will close this).
